### PR TITLE
feat: Filter relations from and to class

### PR DESCRIPTION
**Pull request by jose-ba**
See this issue: [#89](https://github.com/smeghead/php-class-diagram/issues/89)

### CODE REVIEW

**Comment by smeghead** [comment]
@jose-ba 

GREAT WORK!!! Thank you very much.

I am starting to review the updates.

It looked like I was only filtering relations, but the magic of `PlantUML` `remove @unlinked` hides unrelated classes so that I can draw the desired diagram. I did not know about `remove @unlinked`.

I have tried to output a figure with a simple example.

### Normal Diagram

rel-default

### `--from=Entry`

rel-filter-from

### `--to=Entry`

rel-filter-to


I have a concern that the simple words `from` and `to` might be a bit too generic for the option to add. I would prefer a name that is easily recognizable as the target of the filtering. I will consider a few candidates.

**Comment by jose-ba** [comment]
Thank you!

I agree, the names aren't great. Let me know if you can think of any better ones and I'll be happy to make the change.

**Comment by jose-ba** [comment]
I was thinking about `--from-class` and `--to-class` but I think that I like your idea more because they have a common prefix (so it is clear that they do something similar and are related to `--rel-target-depth`) and is more explicit. I will make the change tomorrow if I can. Changing the names is easy obviously, but I have to implement and test the `--rel-target` option, I'm almost sure that I can make it work just by setting `--rel-target-from` and `--rel-target-to` to the same value internally, but I want to test it.

Thank you

**Comment by jose-ba** [comment]
I have added the `--rel-target` option and renamed the other ones. Please review the new option when you can.

**Review by smeghead — CHANGES_REQUESTED** [review]
Thank you!
Please check the two points noted.

**Review by smeghead — APPROVED** [review]
@jose-ba 
Thank you very much!!!

**Pull request merged**
